branches:
  only:
    - develop

language: rust
rust:
  - nightly-2020-10-06

# cache:
#   - cargo

before_script:
  - rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
  - rustup component add rustfmt --toolchain=nightly-2020-10-06
  - rustup component add clippy --toolchain=nightly-2020-10-06 || cargo +nightly-2020-10-06 install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo build
  # - cargo clippy --all-targets --all-features -- -D warnings -A clippy::large-enum-variant -A clippy::try-err -A clippy::redundant-field-names -A clippy::type-complexity -A clippy::or-fun-call -A clippy::redundant-clone
  - cargo test
